#
# File Name: main.yml
# Author : Alexandre Kévin DE FREITAS MARTINS
# Creation Date: 15/8/2025
# Description: This is the main.yml
# Copyright (c) 2025 Alexandre Kévin DE FREITAS MARTINS
# Version: 1.0.0
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the 'Software'), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

name: Build and Push Docker Production Image to GitHub Container Registry

# Environment Variables
env:
    # Github Configuration
    GITHUB_USERNAME: ${{ github.repository_owner }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Trigger the workflow when the Test CI/CD workflow completes successfully on develop branch
on:
    push:
        branches:
            - main
        paths:
            - 'portfolio/**'
            - '.github/workflows/build-docker-prod.yml'

# Build and Push Docker Development Image to GitHub Container Registry
jobs:
    build:
        name: Build & Push Docker Production Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup QEMU
              uses: docker/setup-qemu-action@v3

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  install: true

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ env.GITHUB_USERNAME }}
                  password: ${{ env.GITHUB_TOKEN }}

            - name: Push Docker Production Image
              id: docker_build
              uses: docker/build-push-action@v6
              with:
                  context: "./portfolio"
                  push: true
                  tags: |
                      ghcr.io/alexandredfm/alexandredfm:latest
                      ghcr.io/alexandredfm/alexandredfm:${{ github.sha }}
                  cache-from: type=registry,ref=ghcr.io/alexandredfm/alexandredfm:latest
                  cache-to: type=registry,ref=ghcr.io/alexandredfm/alexandredfm:cache,mode=max
